### PR TITLE
add @types/express as optional peerDependency

### LINKED ISSUE #66: @types/express should be a dependency
as yarn v2 has become more strict with module resolutions, `express-promise-router` should to explicitly define `@types/express` in its dependencies (not `devDependencies`) for the `express` imported in the index.d.ts to be resolved correctly.

as a temporary workaround yarnv2 / typescript users can add the following to their yarnrc.yml

```yml
packageExtensions:
  express-promise-router@*:
    dependencies:
      '@types/express': '^4.11.0'
```

### PR DESCRIPTION
**Pull request by brokenmass**
Closes #66

### CODE REVIEW

**Comment by mormahr** [comment]
Hey, we're using [changesets](https://github.com/atlassian/changesets) to manage the changelog.

Please run `yarn chageset`, select `patch` and enter the change description. Something like "Fix TypeScript dependencies for yarn v2 users, by including `@types/express` as an optional dependency" will do ☺️.

---

Did you look into `optionalDependency`? Whats the difference to `peerDependenciesMeta`?

Thanks for contributing!

**Comment by brokenmass** [comment]
there isn't a real difference between `optionalDependency` and  `peerDependenciesMeta [].optional` (see here : https://github.com/npm/cli/pull/224) and all package manager supports both. `peerDependenciesMeta[].optional` looks cleaner and is going to be a safer long term standard.

@mormahr : pr updated. 

Thanks for you library, I'm glad to contribute back a tiny bit !

**Comment by mormahr** [comment]
Perfect, thanks for sqashing the commits!

**Comment by brokenmass** [comment]
@mormahr : would you be so kind to trigger a release ?

**Comment by mormahr** [comment]
Yes, of course. Been busy yesterday. 😂

**Comment by mormahr** [comment]
@brokenmass Available as v4.0.1

**Pull request merged**
